# Generated by Django 6.0.1 on 2026-02-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_table_remove_order_table_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
