# Generated by Django 6.0.1 on 2026-02-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('preparing', 'Preparing'), ('served', 'Served'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
